package com.tdp2grupo9.utils;

/**
 * Created by emmanuelfls371 on 25/10/2015.
 */
public enum TiposClickeableEnum {DENUNCIAR_PUBLICACION, ENCONTRE_TU_MASCOTA, RECLAMAR_MASCOTA, ELIMINAR_AVISO, ELIMINAR_RECLAMO, POST_ADOPCION, POST_TRANSITO, ELIMINAR_PUBL, EDITAR_PUBL,ELIMINAR_POST_ADOP, ELIMINAR_POST_TRANS };
