import server.Color
import server.Usuario
import server.Castrado
import server.CompatibleCon
import server.Edad
import server.Energia
import server.Especie
import server.PapelesAlDia
import server.Proteccion
import server.Raza
import server.Sexo
import server.Tamanio
import server.VacunasAlDia
import server.Publicacion

class BootStrap {

    def init = { servletContext ->
		new Usuario(facebookId:1156897635,username:'diegomeller',telefono:'112345600',direccion:'Paseo Colon 850',token:'12345',latitud:-58.4621224,longitud:-34.6035515).save()
		new Usuario(username:'email',email:'diego@meller.com',password:'test',telefono:'1145670891',direccion:'Alguna',token:'234567',latitud:-58.4621224,longitud:-34.6035515).save()
        new Castrado(tipo:'Si').save()
        new Castrado(tipo:'No').save()
        new Castrado(tipo:'Desconocido').save()

        new Color(nombre:'Apricot').save()
        new Color(nombre:'Atigrado').save()
        new Color(nombre:'Beige').save()
        new Color(nombre:'Blanco').save()
        new Color(nombre:'Canela').save()
        new Color(nombre:'Fuego').save()
        new Color(nombre:'Gris').save()
        new Color(nombre:'Marrón').save()
        new Color(nombre:'Naranja').save()
        new Color(nombre:'Negro').save()
        new Color(nombre:'Sal y pimienta').save()
        new Color(nombre:'Te').save()
        new Color(nombre:'Tricolor').save()
        new Color(nombre:'Otro').save()

        new CompatibleCon(compatibleCon: 'Niños').save()
        new CompatibleCon(compatibleCon: 'Otras Mascotas').save()

        new Edad(nombre: 'Cachorro (hasta 1 año)').save()
        new Edad(nombre: 'Adulto joven (de 2 a 4 años)').save()
        new Edad(nombre: 'Adulto (de 5 a 9 años)').save()
        new Edad(nombre: 'Viejitos (+ de 10 años)').save()
        new Edad(nombre: 'Desconocido').save()

        new Energia(tipo: 'Muy enérgico').save()
        new Energia(tipo: 'Enérgico').save()
        new Energia(tipo: 'Adicto a la televisión').save()
        new Energia(tipo: 'No aplica').save()

        new Especie(tipo:'Perro').save()
        new Especie(tipo:'Gato').save()

        new PapelesAlDia(tipo: 'Si').save()
        new PapelesAlDia(tipo: 'No').save()
        new PapelesAlDia(tipo: 'No Aplica').save()

        new Proteccion(tipo:'Guardián').save()
        new Proteccion(tipo:'Algo protector').save()
        new Proteccion(tipo:'Poco o nada protector').save()
        new Proteccion(tipo:'No aplica').save()

        new Raza(nombre:'Akita americano',especie: 1).save()
        new Raza(nombre:'Basset Griffon Vendeen',especie:1).save()
        new Raza(nombre:'Basset Hound',especie:1).save()
        new Raza(nombre:'Bichon Frise',especie:1).save()
        new Raza(nombre:'Border Collie',especie:1).save()
        new Raza(nombre:'Boston Terrier',especie:1).save()
        new Raza(nombre:'Bóxer',especie:1).save()
        new Raza(nombre:'Boyero de Berna',especie:1).save()
        new Raza(nombre:'Bulldog',especie:1).save()
        new Raza(nombre:'Bulldog francés',especie:1).save()
        new Raza(nombre:'Cairn Terrier',especie:1).save()
        new Raza(nombre:'Cavalier King Charles Spaniel',especie:1).save()
        new Raza(nombre:'Chihuahua',especie:1).save()
        new Raza(nombre:'Chow Chow',especie:1).save()
        new Raza(nombre:'Clumber Spaniel',especie:1).save()
        new Raza(nombre:'Cocker Spaniel Americano',especie:1).save()
        new Raza(nombre:'Cocker Spaniel Inglés',especie:1).save()
        new Raza(nombre:'Collie',especie:1).save()
        new Raza(nombre:'Dachshund',especie:1).save()
        new Raza(nombre:'Dálmata',especie:1).save()
        new Raza(nombre:'Doberman',especie:1).save()
        new Raza(nombre:'Flat Coated Retriever',especie:1).save()
        new Raza(nombre:'Galgo',especie:1).save()
        new Raza(nombre:'Golden Retriever',especie:1).save()
        new Raza(nombre:'Gran Danés',especie:1).save()
        new Raza(nombre:'Havanese',especie:1).save()
        new Raza(nombre:'Husky Siberiano',especie:1).save()
        new Raza(nombre:'Labrador Retriever',especie:1).save()
        new Raza(nombre:'Lancashire Heeler',especie:1).save()
        new Raza(nombre:'Leonberger',especie:1).save()
        new Raza(nombre:'Malamute de Alaska',especie:1).save()
        new Raza(nombre:'Maltés',especie:1).save()
        new Raza(nombre:'Mastín napolitano',especie:1).save()
        new Raza(nombre:'Mestizo',especie:1).save()
        new Raza(nombre:'Papillon',especie:1).save()
        new Raza(nombre:'Parson Russell Terrier',especie:1).save()
        new Raza(nombre:'Pastor Alemán',especie:1).save()
        new Raza(nombre:'Pastor Australiano',especie:1).save()
        new Raza(nombre:'Pastor de Shetland',especie:1).save()
        new Raza(nombre:'Pekinés',especie:1).save()
        new Raza(nombre:'Pembroke Corgi Galés',especie:1).save()
        new Raza(nombre:'Perro de Canaan',especie:1).save()
        new Raza(nombre:'Perro Ovejero de Asia Central',especie:1).save()
        new Raza(nombre:'Pinscher miniatura',especie:1).save()
        new Raza(nombre:'Pitbull terrier',especie:1).save()
        new Raza(nombre:'Pomeranio',especie:1).save()
        new Raza(nombre:'Poodle',especie:1).save()
        new Raza(nombre:'Pug',especie:1).save()
        new Raza(nombre:'Puli húngaro',especie:1).save()
        new Raza(nombre:'Rhodesian Ridgeback',especie:1).save()
        new Raza(nombre:'Rottweiler',especie:1).save()
        new Raza(nombre:'San Bernardo',especie:1).save()
        new Raza(nombre:'Schnauzer Miniatura',especie:1).save()
        new Raza(nombre:'Shar Pei',especie:1).save()
        new Raza(nombre:'Shiba Inu',especie:1).save()
        new Raza(nombre:'Shih Tzu',especie:1).save()
        new Raza(nombre:'Spaniel Bretón',especie:1).save()
        new Raza(nombre:'Springer Spaniel Inglés',especie:1).save()
        new Raza(nombre:'Staffordshire Terrier',especie:1).save()
        new Raza(nombre:'Terranova',especie:1).save()
        new Raza(nombre:'Terrier Escocés',especie:1).save()
        new Raza(nombre:'Terrier montañés del oeste',especie:1).save()
        new Raza(nombre:'Terrier Yorkshire',especie:1).save()
        new Raza(nombre:'Viejo Pastor Inglés',especie:1).save()
        new Raza(nombre:'Vizsla',especie:1).save()
        new Raza(nombre:'Weimaraner',especie:1).save()
        new Raza(nombre:'Otra',especie:1).save()
        new Raza(nombre:'Abisinios',especie:2).save()
        new Raza(nombre:'Americano de pelo áspero',especie:2).save()
        new Raza(nombre:'Americanos de cola anillada',especie:2).save()
        new Raza(nombre:'Americanos de pelo corto',especie:2).save()
        new Raza(nombre:'Anatolia',especie:2).save()
        new Raza(nombre:'Angora turco',especie:2).save()
        new Raza(nombre:'Azul Ruso',especie:2).save()
        new Raza(nombre:'Balinés',especie:2).save()
        new Raza(nombre:'Bengala',especie:2).save()
        new Raza(nombre:'Birmano',especie:2).save()
        new Raza(nombre:'Bobtail Americano',especie:2).save()
        new Raza(nombre:'Bobtail japonés',especie:2).save()
        new Raza(nombre:'Bombay',especie:2).save()
        new Raza(nombre:'Bosque de noruega',especie:2).save()
        new Raza(nombre:'Británico de pelo corto',especie:2).save()
        new Raza(nombre:'Burmés',especie:2).save()
        new Raza(nombre:'Burmés europeo',especie:2).save()
        new Raza(nombre:'California Spangled',especie:2).save()
        new Raza(nombre:'Chartreux',especie:2).save()
        new Raza(nombre:'Chausie',especie:2).save()
        new Raza(nombre:'Colorpoint de pelo corto',especie:2).save()
        new Raza(nombre:'Cornish rex',especie:2).save()
        new Raza(nombre:'Curl americano',especie:2).save()
        new Raza(nombre:'Devon rex',especie:2).save()
        new Raza(nombre:'Don',especie:2).save()
        new Raza(nombre:'Europeo de pelo corto',especie:2).save()
        new Raza(nombre:'Fold escocés',especie:2).save()
        new Raza(nombre:'Habana brown',especie:2).save()
        new Raza(nombre:'Himalayo',especie:2).save()
        new Raza(nombre:'Javanés',especie:2).save()
        new Raza(nombre:'Khao Manee',especie:2).save()
        new Raza(nombre:'Korat',especie:2).save()
        new Raza(nombre:'LaPerm',especie:2).save()
        new Raza(nombre:'Maine Coon',especie:2).save()
        new Raza(nombre:'Manx',especie:2).save()
        new Raza(nombre:'Mau egipcio',especie:2).save()
        new Raza(nombre:'Minskin',especie:2).save()
        new Raza(nombre:'Munchkin',especie:2).save()
        new Raza(nombre:'Nibelungo',especie:2).save()
        new Raza(nombre:'Ocicat',especie:2).save()
        new Raza(nombre:'Oriental',especie:2).save()
        new Raza(nombre:'Persas',especie:2).save()
        new Raza(nombre:'Peterbald',especie:2).save()
        new Raza(nombre:'Pixie-Bob',especie:2).save()
        new Raza(nombre:'Ragamuffin',especie:2).save()
        new Raza(nombre:'Ragdoll',especie:2).save()
        new Raza(nombre:'Savannah',especie:2).save()
        new Raza(nombre:'Selkirk rex',especie:2).save()
        new Raza(nombre:'Siamés',especie:2).save()
        new Raza(nombre:'Siberiano',especie:2).save()
        new Raza(nombre:'Singapura',especie:2).save()
        new Raza(nombre:'Snowshoe',especie:2).save()
        new Raza(nombre:'Sokoke',especie:2).save()
        new Raza(nombre:'Somalíes',especie:2).save()
        new Raza(nombre:'Sphynx',especie:2).save()
        new Raza(nombre:'Tiffanie',especie:2).save()
        new Raza(nombre:'Tonikés',especie:2).save()
        new Raza(nombre:'Toyger',especie:2).save()
        new Raza(nombre:'Van turco',especie:2).save()
        new Raza(nombre:'Otra',especie:2).save()

        new Sexo(tipo: 'Macho').save()
        new Sexo(tipo: 'Hembra').save()
        new Sexo(tipo: 'Desconocido').save()

        new Tamanio(tipo: 'Chico').save()
        new Tamanio(tipo: 'Mediano').save()
        new Tamanio(tipo: 'Grande').save()

        new VacunasAlDia(tipo:'Si').save()
        new VacunasAlDia(tipo:'No').save()
        new VacunasAlDia(tipo:'Desconocido').save()
				
		new Publicacion(nombreMascota:'bobby',publicador:2,color:1,castrado:1,compatibleCon:1,edad:1,energia:1,especie:2,papelesAlDia:1,proteccion:2,raza:1,sexo:1,tamanio:1,vacunasAlDia:1,latitud:-58.367289,longitud:-34.6454526).save()
		new Publicacion(nombreMascota:'otto',publicador:2,color:1,castrado:1,compatibleCon:1,edad:1,energia:1,especie:2,papelesAlDia:1,proteccion:2,raza:1,sexo:1,tamanio:1,vacunasAlDia:1,latitud:-58.4226265,longitud:-34.6098885).save()
		new Publicacion(nombreMascota:'panchita tiene pelos largos blancos y sucios por estar en el patio',publicador:2,color:1,castrado:1,compatibleCon:1,edad:1,energia:1,especie:2,papelesAlDia:1,proteccion:2,raza:1,sexo:1,tamanio:1,vacunasAlDia:1,latitud:-58.5242344,longitud:-34.6192385).save()
		

    }
    def destroy = {
    }
}

